# Generated by Django 4.2.15 on 2026-06-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='consent_at',
            field=models.DateTimeField(blank=True, help_text='When the person opted in (their first inbound message).', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='consent_message_sid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='consent_text',
            field=models.TextField(blank=True, help_text='The inbound message body that constitutes consent / opt-in.'),
        ),
        migrations.AddField(
            model_name='person',
            name='opted_out',
            field=models.BooleanField(default=False, help_text='Set when the person replies STOP.'),
        ),
        migrations.AddField(
            model_name='person',
            name='opted_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
