# Generated by Django 4.2.15 on 2026-06-26 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_person_consent_at_person_consent_message_sid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='The order in which questions are asked.', unique=True)),
                ('key', models.SlugField(help_text='Stable identifier used when recording answers.', unique=True)),
                ('text', models.TextField()),
                ('counts_toward_score', models.BooleanField(default=True, help_text="Whether a 'yes' to this question counts toward the screening score.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='entry_criterion_met',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='feature_yes_count',
        ),
        migrations.AddField(
            model_name='conversation',
            name='yes_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_key',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='screening.question'),
        ),
    ]
